{
    "th06 Bomb Reimu A": "Spirit Sign \"Fantasy Seal\"",
    "th06 Bomb Reimu B": "Dream Sign \"Evil-Sealing Circle\"",
    "th06 Bomb Marisa A": "Magic Sign \"Stardust Reverie\"",
    "th06 Bomb Marisa B": "Love Sign \"Master Spark\"",
    "th06 Stats ReimuA": "Reimu Hakurei (A)",
    "th06 Stats ReimuB": "Reimu Hakurei (B)",
    "th06 Stats MarisaA": "Marisa Kirisame (A)",
    "th06 Stats MarisaB": "Marisa Kirisame (B)",
    "th07 Menu Start": "Play the game",
    "th07 Menu Extra Start": "Play extra stage",
    "th07 Menu Practice Start": "Choose a stage to practice",
    "th07 Menu Result": "View score and spell card history",
    "th07 Menu Music Room": "Listen to music",
    "th07 Menu Replay": "Enjoy watching replays",
    "th07 Menu Option": "Change various settings",
    "th07 Menu Quit": "Quit the game",
    "th07 Option Player": "Number of lives to start with. (default 3)",
    "th07 Option Graphic": "Number of colors on screen. 32Bit looks better.",
    "th07 Option BGM": "BGM playback method. (default WAV)",
    "th07 Option Sound": "Toggle sound effects",
    "th07 Option Window Mode": "Switch between window and fullscreen mode",
    "th07 Option Slow Mode": "Slow down when lots of bullets on screen (no hiscore or replay)",
    "th07 Option Reset": "Restore default settings",
    "th07 Option Key Config": "Change pad button configuration",
    "th07 Option Quit": "Leave settings menu",
    "th07 Key Shot": "Choose shot/confirm button",
    "th07 Key Bomb": "Choose bomb/cancel button",
    "th07 Key Slow": "Choose button to move slower",
    "th07 Key Skip": "Choose button to skip messages",
    "th07 Key Pause": "Choose pause button",
    "th07 Key Up": "Choose button to move up",
    "th07 Key Down": "Choose button to move down",
    "th07 Key Left": "Choose button to move left",
    "th07 Key Right": "Choose button to move right",
    "th07 Key ShotSlow": "Move slower when holding down shot key",
    "th07 Key Reset": "Restore default buttons",
    "th07 Key Quit": "Leave button config",
    "th07 Bomb Reimu A unfocused": "Spirit Sign \"Fantasy Seal -Spread-\"",
    "th07 Bomb Reimu A focused": "Spirit Sign \"Fantasy Seal -Concentrate-\"",
    "th07 Bomb Reimu B focused": "Dream Sign \"Duplex Barrier\"",
    "th07 Bomb Marisa A focused": "Magic Sign \"Milky Way\"",
    "th07 Bomb Marisa B unfocused": "Love Sign \"Non-Directional Laser\"",
    "th07 Bomb Sakuya A unfocused": "Illusion Sign \"Indiscriminate\"",
    "th07 Bomb Sakuya A focused": "Illusion Sign \"Killing Doll\"",
    "th07 Bomb Sakuya B unfocused": "Time Sign \"Perfect Square\"",
    "th07 Bomb Sakuya B focused": "Time Sign \"Private Square\"",
    "th07 16bits textures": "Force using 16-bit textures",
    "th07 DirectInput": "Don't use DirectInput for input control",
    "th07 BGM memory": "Preload BGM in memory",
    "th07 draw screen": "Redraw HUD every frame",
    "th07 VSync": "Disable vertical synchronization",
    "th07 fullscreen": "Full screen (Rec.)",
    "th07 low effects": "Min.",
    "th07 medium effects": "Moderate",
    "th07 high effects": "Max (Rec.)",
    "th07 32bits mode": "32-bit (default)",
    "th07 effect quality": "Effect quality",
    "th07 Stats Time Since Startup": "Time running  %.2d:%.2d:%.2d",
    "th07 Stats Total Playtime": "Time played   %.2d:%.2d:%.2d",
    "th07 Stats Total (All Characters)": "All Characters",
    "th07 Stats ReimuA": "Reimu Hakurei (A)",
    "th07 Stats ReimuB": "Reimu Hakurei (B)",
    "th07 Stats MarisaA": "Marisa Kirisame (A)",
    "th07 Stats MarisaB": "Marisa Kirisame (B)",
    "th07 Stats SakuyaA": "Sakuya Izayoi (A)",
    "th07 Stats SakuyaB": "Sakuya Izayoi (B)",
    "th07 Stats Play Count": "Games played           Easy Norm Hard Luna Extra Total",
    "th07 Stats Clear Count": "Times cleared  %6d %6d %6d %6d %6d %6d",
    "th07 Stats Retries": "Times retried  %6d %6d %6d %6d %6d %6d",
    "th07 Stats Play Count +Phantasm": "Games played           Easy Norm Hard Luna Extra Phants Total",
    "th07 Stats Clear Count +Phantasm": "Times cleared  %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Continue": "Times continued  %6d %6d %6d %6d %6d %6d",
    "th07 Stats Continue +Phantasm": "Times continued  %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Practice": "Times practiced  %6d %6d %6d %6d %6d %6d",
    "th07 Stats Practice +Phantasm": "Times practiced  %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Retries +Phantasm": "Times retried  %6d %6d %6d %6d %6d %6d %6d",
    "th07 Spell Result Character Select": "%s  %3d/%3d captured (up/dn changes char)",
    "th07 Stats Header Total": "Total",
    "th07 config": "Touhou Youyoumu - Environment Custom Program"
}