{
    "th06_01": "Scarlet Beyond a Crimson Dream",
    "th06_02": "A Soul as Red as a Ground Cherry",
    "th06_03": "Apparitions Stalk the Night",
    "th06_04": "Lunate Elf",
    "th06_05": "Beloved Tomboyish Daughter",
    "th06_06": "Shanghai Teahouse ~ Chinese Tea",
    "th06_07": "Shanghai Alice of Meiji 17",
    "th06_08": "Voile, the Magic Library",
    "th06_09": "Locked Girl ~ The Girl's Secret Room",
    "th06_10": "The Maid and the Pocket Watch of Blood",
    "th06_11": "Lunar Clock ~ Luna Dial",
    "th06_12": "The Young Descendant of Tepes",
    "th06_13": "Septette for the Dead Queen",
    "th06_14": "The Centennial Festival for Magical Girls",
    "th06_15": "U.N. Owen was her?",
    "th06_16": "Crimson Beyond a Fleeting Eternity",
    "th06_17": "Crimson Belvedere ~ Eastern Dream...",
    "th07_01": "Mystic Dream ~ Snow or Cherry Petal",
    "th07_02": "Paradise ~ Deep Mountain",
    "th07_03": "Crystallized Silver",
    "th07_04": "The Fantastic Legend of Tohno",
    "th07_05": "Diao ye zong (Withered Leaf)",
    "th07_06": "The Doll Maker of Bucuresti",
    "th07_07": "Doll Judgment ~ The girl who played with people's shapes",
    "th07_08": "The capital city of flowers in the sky",
    "th07_09": "Phantom Ensemble",
    "th07_10": "Mystic Oriental Dream ~ Ancient Temple",
    "th07_11": "Hiroari Shoots a Strange Bird ~ Till When?",
    "th07_12": "Ultimate Truth",
    "th07_13": "Bloom nobly, cherry blossoms of Sumizome ~ Border of Life",
    "th07_14": "Border of Life",
    "th07_15": "Charming Domination",
    "th07_16": "A Maiden's Illusionary Funeral ~ Necro-Fantasy",
    "th07_17": "Charming Domination ~ Who done it?",
    "th07_18": "Necrofantasia",
    "th07_19": "Dream of a Spring Breeze",
    "th07_20": "Sakura, Sakura ~ Japanize Dream"
}