{
    "0": "Frost Sign \"Frost Columns\"",
    "1": "Frost Sign \"Frost Columns -Lunatic-\"",
    "2": "Cold Sign \"Lingering Cold -Easy-\"",
    "3": "Cold Sign \"Lingering Cold\"",
    "4": "Cold Sign \"Lingering Cold -Hard-\"",
    "5": "Cold Sign \"Lingering Cold -Lunatic-\"",
    "6": "Winter Sign \"Flower Wither Away -Easy-\"",
    "7": "Winter Sign \"Flower Wither Away\"",
    "8": "White Sign \"Undulation Ray\"",
    "9": "Mystic Sign \"Table Turning\"",
    "10": "Wizard Sign \"Phoenix Egg -Easy-\"",
    "11": "Wizard Sign \"Phoenix Egg\"",
    "12": "Wizard Sign \"Phoenix Spread Wings\"",
    "13": "Wizard Sign \"Phoenix Spread Wings L\"",
    "14": "Shikigami Sign \"Pentagram Flight E\"",
    "15": "Shikigami Sign \"Pentagram Flight\"",
    "16": "Yin Yang \"Douman-Seiman\"",
    "17": "Ying Yang \"Large Pentagram Crest\"",
    "18": "Heaven Sign \"Immortal Sage's Rumbling E\"",
    "19": "Heaven Sign \"Immortal Sage's Rumbling\"",
    "20": "Flight Sign \"Flight of Idaten\"",
    "21": "Child Sign \"Crusading Cherub's Rampage\"",
    "22": "Wizard Sign \"Incarnate Immortal Sage E\"",
    "23": "Wizard Sign \"Incarnate Immortal Sage\"",
    "24": "Oni Sign \"Konjin of the Demon's Gate\"",
    "25": "Direction Sign \"Kimontonkou\"",
    "26": "Puppeteer Sign \"Maiden's Bunraku\"",
    "27": "Puppeteer Sign \"Maiden's Bunraku L\"",
    "28": "Blue Sign \"Benevolent French Dolls E\"",
    "29": "Blue Sign \"Benevolent French Dolls\"",
    "30": "Blue Sign \"Benevolent French Dolls H\"",
    "31": "Blue Sign \"Benevolent Orleans Dolls\"",
    "32": "Scarlet Sign \"Red-Haired Dutch Dolls E\"",
    "33": "Scarlet Sign \"Red-Haired Dutch Dolls\"",
    "34": "White Sign \"Chalk-White Russian Dolls\"",
    "35": "White Sign \"Chalk-White Russian Dolls L\"",
    "36": "Darkness Sign \"Foggy London Dolls E\"",
    "37": "Darkness Sign \"Foggy London Dolls\"",
    "38": "Cycle Sign \"Reincarnating Tibetan Dolls\"",
    "39": "Elegant Sign \"Spring Kyoto Dolls\"",
    "40": "Curse \"Eerily Luminous Shanghai Dolls E\"",
    "41": "Curse \"Eerily Luminous Shanghai Dolls\"",
    "42": "Curse \"Eerily Luminous Shanghai Dolls H\"",
    "43": "Curse \"Hanged Hourai Dolls\"",
    "44": "Noisy Sign \"Phantom Dinning E\"",
    "45": "Noisy Sign \"Phantom Dinning\"",
    "46": "Noisy Sign \"Live Poltergeist\"",
    "47": "Noisy Sign \"Live Poltergeist L\"",
    "48": "String Performance \"Guarneri del Gesu E\"",
    "49": "String Performance \"Guarneri del Gesu\"",
    "50": "Spirit Strings \"Stradivarius\"",
    "51": "Fake Strings \"Pseudo Stradivarius\"",
    "52": "Trumpet Ghost \"Hino Phantasm E\"",
    "53": "Trumpet Ghost \"Hino Phantasm\"",
    "54": "Dark Trumpet \"Ghost Clifford\"",
    "55": "Trumpet Ghost \"Ghost Clifford L\"",
    "56": "Dark Keys \"Fazioli Dark Performance E\"",
    "57": "Dark Keys \"Fazioli Dark Performance\"",
    "58": "Key Ghost \"Bosendorfer Spirit Perf.\"",
    "59": "Key Ghost \"Bosendorfer Spirit Perf. L\"",
    "60": "Requiem \"Prism Concerto E\"",
    "61": "Requiem \"Prism Concerto\"",
    "62": "Noisy Funeral \"Stygian Riverside\"",
    "63": "Noisy Funeral \"Stygian Riverside L\"",
    "64": "Great Requiem \"Concerto Grosso E\"",
    "65": "Great Requiem \"Concerto Grosso\"",
    "66": "Great Requiem \"Revised Concerto Grosso\"",
    "67": "Great Requiem \"Wonderous Concerto Grosso\"",
    "68": "Ghost Sword \"Fasting of the Young Gaki E\"",
    "69": "Ghost Sword \"Fasting of the Young Gaki\"",
    "70": "Gaki Sword \"Storybook of the Gaki Realm\"",
    "71": "Hungry King Sword \"Ten Kings' Retribution\"",
    "72": "Hell Realm Sword \"200 Yojana in 1 Slash E\"",
    "73": "Hell Realm Sword \"200 Yojana in 1 Slash\"",
    "74": "Hell Flame Sword \"Flashing Slash Formation\"",
    "75": "Hell God Sword \"God's Flashing Slash\"",
    "76": "Brute Sword \"Karmic Punishment E\"",
    "77": "Brute Sword \"Karmic Punishment\"",
    "78": "Asura Sword \"Worldly Attachment\"",
    "79": "Asura Sword \"Worldly Attachment L\"",
    "80": "Human Sword \"Delusion of Enlightenment E\"",
    "81": "Human Sword \"Delusion of Enlightenment\"",
    "82": "Human Era Sword \"Approaching Disillusion\"",
    "83": "Human God Sword \"Eternal Truth\"",
    "84": "Heaven's Sword \"Five Signs of the Deva E\"",
    "85": "Heaven's Sword \"Five Signs of the Deva\"",
    "86": "Deva Realm Sword \"Seven Sins\"",
    "87": "Deva God Sword \"Components of Konpaku\"",
    "88": "Six Realms Sword \"Ageless Obssession E\"",
    "89": "Six Realms Sword \"Ageless Obssession\"",
    "90": "Six Realms Sword \"Ageless Obssession H\"",
    "91": "Six Realms Sword \"Ageless Obssession L\"",
    "92": "Lost Soul's Village \"-Wandering Soul-\"",
    "93": "Lost Soul's Village \"-Fatal Sin-\"",
    "94": "Lost Soul's Village \"-Trackless Path-\"",
    "95": "Lost Soul's Village \"-Suicide-\"",
    "96": "Deadly Dance \"Mortality -Illusion-\"",
    "97": "Deadly Dance \"Mortality -Dead Butterfly-\"",
    "98": "Deadly Dance \"Mortality -Poisonous Moth-\"",
    "99": "Deadly Dance \"Mortality -Demon World-\"",
    "100": "Flowery Soul \"Ghost Butterfly\"",
    "101": "Flowery Soul \"Swallowtail Butterfly\"",
    "102": "Flowery Soul \"Deep-Rooted Butterfly\"",
    "103": "Flowery Soul \"Butterfly Delusion\"",
    "104": "\"Repository of Hirokawa -False Soul-\"",
    "105": "\"Repository of Hirokawa -Ghost-\"",
    "106": "\"Repository of Hirokawa -Phantom-\"",
    "107": "\"Repository of Hirokawa -Divine Soul-\"",
    "108": "\"Sumizome Perfect Blossom -Seal-\"",
    "109": "\"Sumizome Perfect Blossom -Getting Lost-\"",
    "110": "\"Sumizome Perfect Blossom -Deep Sleep-\"",
    "111": "\"Sumizome Perfect Blossom -Bloom-\"",
    "112": "\"Resurrection Butterfly -10%% Reflowering-\"",
    "113": "\"Resurrection Butterfly -30%% Reflowering-\"",
    "114": "\"Resurrection Butterfly -50%% Reflowering-\"",
    "115": "\"Resurrection Butterfly -80%% Reflowering-\"",
    "116": "Oni Sign \"Blue Oni Red Oni\"",
    "117": "Oni God \"Soaring Guardian God\"",
    "118": "Shikigami \"Wizard Fox Thoughts\"",
    "119": "Shikigami \"Banquet of 12 General Gods\"",
    "120": "Radiance \"Fox-Tanuki Youkai Laser\"",
    "121": "Radiance \"Charming Siege from All Sides\"",
    "122": "Radiance \"Princess Tenko -Illusion-\"",
    "123": "Shikigami's Shot \"Ultimate Buddhist\"",
    "124": "Shikigami's Shot \"Unilateral Contact\"",
    "125": "Shikigami \"Chen\"",
    "126": "\"Kokkuri-san's Contract\"",
    "127": "Illusion God \"Descent of Izuna Gongen\"",
    "128": "Shikigami \"Protection of Zenki and Goki\"",
    "129": "Shikigami \"Dakini's Heavenly Possession\"",
    "130": "Boundary \"Curse of Dreams and Reality\"",
    "131": "Boundary \"Balance of Motion and Stillness\"",
    "132": "Boundary \"Mesh of Light and Darkness\"",
    "133": "Evil Spirits \"Xanadu of Straight and Curve\"",
    "134": "Evil Spirits \"Yukari's Spiriting Away\"",
    "135": "Evil Spirits \"Butterfly in the Zen Temple\"",
    "136": "Sinister Spirits \"Double Death Butterfly\"",
    "137": "Shikigami \"Ran Yakumo\"",
    "138": "\"Boundary of Humans and Youkai\"",
    "139": "Bounded Field \"Boundary of Life and Death\"",
    "140": "Yukari's Arcanum \"Danmaku Bounded Field\""
}